// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVN2hw2XXPPpqRngxQW3zbZtyIHzx8YNk',
    appId: '1:643278070250:web:77eb1a002dadcbbf595293',
    messagingSenderId: '643278070250',
    projectId: 'donate-clothes-fb39f',
    authDomain: 'donate-clothes-fb39f.firebaseapp.com',
    storageBucket: 'donate-clothes-fb39f.appspot.com',
    measurementId: 'G-3752YBJ0G1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj2rUHI0wTv7BJAkv7pK5oIi8OcTtLuEE',
    appId: '1:643278070250:android:8d3a0fadb85b063a595293',
    messagingSenderId: '643278070250',
    projectId: 'donate-clothes-fb39f',
    storageBucket: 'donate-clothes-fb39f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Ovfa8uUWl_hVGubHFT4Tj17uLWhH9cE',
    appId: '1:643278070250:ios:52c9a0ebcc10196e595293',
    messagingSenderId: '643278070250',
    projectId: 'donate-clothes-fb39f',
    storageBucket: 'donate-clothes-fb39f.appspot.com',
    iosBundleId: 'com.example.donateClothes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Ovfa8uUWl_hVGubHFT4Tj17uLWhH9cE',
    appId: '1:643278070250:ios:9ccd4b13c5369c7f595293',
    messagingSenderId: '643278070250',
    projectId: 'donate-clothes-fb39f',
    storageBucket: 'donate-clothes-fb39f.appspot.com',
    iosBundleId: 'com.example.donateClothes.RunnerTests',
  );
}
